version: '3'
services:
    pcap_processor:
        build: .
        container_name: pcap_processor_service
        volumes:
            - ./data/pcap:/app/data/pcap
            - ./data/output:/app/data/output
        environment:
            - PCAP_FILE=/app/data/pcap/capture-1-0.pcap
            - CSV_FILE=/app/data/output/features.csv
